### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by mziadd** [moovida/flutter_geopackage#5]
Hi @moovida, Sometimes I am getting an error called "database is locked...etc", i suspect this is because GeoPackage not uses async methods, should I consider migrating methods to async way? or is there are any workarounds for this?

**Comment by moovida** [comment]
Hi @mohammedX6 , that is odd, it never happened to me. Do you have a way to reproduce this? 
GeoPackage relies on sqlite, which is not thread safe, so the whole chain of libraries on top of it are not async. Therefore I would avoid async usage.

**Comment by mziadd** [comment]
@moovida It's hard to reproduce, I think when the device is becoming slow it's happening, I saw in your SQLite implementation there is a Transaction method, could this help?

**Comment by moovida** [comment]
I am not really sure. If you are experiencing locks, then I assume you are accessing the database in a multithreaded environment for writing purposes (I don't think it should be locked otherwise). Transactions won't help you in this case. You would anyways have to put the writing operations in line and execute them in sync.

**Comment by mziadd** [comment]
my application has isolates accessing the GeoPackage database, I think you give me a good hint, I will debug more to find the problem.
thanks @moovida

**Comment by mziadd** [comment]
Hi, @moovida  I just find the cause of the problem from accessing the GeoPackage in the isolate while another method is calling the GeoPackage file in the main thread.

**Comment by moovida** [comment]
Ah, ok, then that makes sense. great!
